version: "3"
 
services:
  job-portal:
    container_name: job
    image: "job-portal-api"
    ports:
      - "8080:8080"
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .app.env
      - .auth.env
      - .app.postgres.env
      - .app.redis.env
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .postgres.env
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .redis.env
